
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="?page=home">ChienRouleau</a>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="?page=home">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="?page=chat">Chat</a></li>
      </ul>

     <ul class="nav navbar-nav navbar-right">
          <li class="register"><a href="#">Bonjour <span class="login"><?php echo $_SESSION['login']; ?></span></a></li>
            <li class="register"><?php require('apps/logout.php'); ?></li>
          </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>