<div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
    	<div class="panel panel-default">
    		<div class="panel-heading">
		    		<h3 class="panel-title">Enregistrez votre compte</h3>
		 			</div>
		 			<div class="panel-body">
		    		<form role="form" method="post" action="?page=users">
		    			<div style="background-color:red;"><?=implode('<br/>', $errors)?></div>
    					

		    			<div class="form-group">
    						<input type="text" name="log" id="login" class="form-control input-sm" placeholder="Pseudo" value="<?=htmlentities($log)?>">
    					</div>

		    				<div>
		    					<div class="form-group">
		    						<input type="password" name="pass" id="password" class="form-control input-sm" value='<?=htmlentities($pass)?>' placeholder="Mot de passe">
		    					</div>
		    				</div>
		    			</div>
		    			
		    			<input type="submit" value="Enregistrer" class="btn btn-info btn-block">
		    		
		    		</form>
		    	
		    	</div>
    		</div>
		</div>
	</div>